# Generated by Django 4.1 on 2022-09-01 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.IntegerField(blank=True, db_column='followers', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.IntegerField(blank=True, db_column='following', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, db_column='profile_image', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(db_column='password', max_length=256),
        ),
    ]
