# Generated by Django 4.1 on 2022-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_video_topics_video_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='topic',
        ),
        migrations.AddField(
            model_name='video',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='api.topic'),
        ),
    ]
