# Generated by Django 4.1 on 2022-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_id_myuser_id_myuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='topic',
        ),
        migrations.AddField(
            model_name='video',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='api.topic'),
        ),
    ]
