# Generated by Django 4.0.6 on 2022-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
