# Generated by Django 4.1 on 2022-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_video_topic_video_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
