# Generated by Django 4.1 on 2022-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, db_column='full_name', max_length=40, null=True),
        ),
    ]
