# Generated by Django 4.0.6 on 2022-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_thumbnail_alter_video_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='video',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, to='api.watchlist'),
        ),
    ]
