# Generated by Django 4.1 on 2022-09-05 15:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_myuser_first_name_remove_myuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, db_column='profile_image', null=True, upload_to=api.models.upload_to),
        ),
    ]
