# Generated by Django 4.1 on 2022-08-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_video_watchlist_video_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='video',
            name='watchlists',
            field=models.ManyToManyField(blank=True, to='api.watchlist'),
        ),
    ]
